# Generated by Django 5.0.7 on 2024-08-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('max_temp', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('total_precipitation', models.FloatField()),
                ('sunrise_hour', models.TimeField()),
                ('sunset_hour', models.TimeField()),
            ],
            options={
                'verbose_name': 'Weather Forecast',
                'verbose_name_plural': 'Weather Forecasts',
                'unique_together': {('date', 'city')},
            },
        ),
    ]
