# Generated by Django 5.0.7 on 2024-08-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costiciRoxana', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherforecast',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='weatherforecast',
            unique_together=set(),
        ),
    ]
